/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package isp_manager;

/**
 *
 * @author King Nothing
 */
public class addCustomerOptions extends javax.swing.JPanel {

    /**
     * Creates new form addCustomerOptions
     */
    public addCustomerOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCustomerOptions = new javax.swing.JPanel();
        addCustomerLabel = new javax.swing.JLabel();

        addCustomerOptions.setBackground(new java.awt.Color(255, 255, 255));
        addCustomerOptions.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                addCustomerOptionsHierarchyChanged(evt);
            }
        });

        addCustomerLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        addCustomerLabel.setForeground(new java.awt.Color(51, 51, 51));
        addCustomerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addCustomerLabel.setText("Add Customer");

        javax.swing.GroupLayout addCustomerOptionsLayout = new javax.swing.GroupLayout(addCustomerOptions);
        addCustomerOptions.setLayout(addCustomerOptionsLayout);
        addCustomerOptionsLayout.setHorizontalGroup(
            addCustomerOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCustomerOptionsLayout.createSequentialGroup()
                .addContainerGap(509, Short.MAX_VALUE)
                .addComponent(addCustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(483, 483, 483))
        );
        addCustomerOptionsLayout.setVerticalGroup(
            addCustomerOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addCustomerLabel)
                .addContainerGap(743, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1241, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addCustomerOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addCustomerOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerOptionsHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_addCustomerOptionsHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerOptionsHierarchyChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addCustomerLabel;
    private javax.swing.JPanel addCustomerOptions;
    // End of variables declaration//GEN-END:variables
}
