/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package isp_manager;

/**
 *
 * @author King Nothing
 */
public class customerPanel extends javax.swing.JPanel {

    /**
     * Creates new form customerPanel
     */
    public customerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        addCustomerPanel = new javax.swing.JPanel();
        addCustomerButton = new javax.swing.JButton();
        addCustomerPanel1 = new javax.swing.JPanel();
        customerPackageButton = new javax.swing.JButton();
        searchCustomerPanel2 = new javax.swing.JPanel();
        searchCustomerButton = new javax.swing.JButton();
        listCustomerPanel3 = new javax.swing.JPanel();
        listOfCustomerButton = new javax.swing.JButton();
        customerPaymentPanel = new javax.swing.JPanel();
        customerPaymentButton = new javax.swing.JButton();
        customerReportPanel = new javax.swing.JPanel();
        customerReportButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1268, 857));
        setRequestFocusEnabled(false);

        CustomerPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("New");

        addCustomerPanel.setBackground(new java.awt.Color(159, 164, 169));
        addCustomerPanel.setForeground(new java.awt.Color(53, 144, 243));

        addCustomerButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addCustomerButton.setForeground(new java.awt.Color(51, 51, 51));
        addCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isp_manager/resources/add-user.png"))); // NOI18N
        addCustomerButton.setText("Add Customer");
        addCustomerButton.setBorder(null);
        addCustomerButton.setContentAreaFilled(false);
        addCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addCustomerPanelLayout = new javax.swing.GroupLayout(addCustomerPanel);
        addCustomerPanel.setLayout(addCustomerPanelLayout);
        addCustomerPanelLayout.setHorizontalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );
        addCustomerPanelLayout.setVerticalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        addCustomerPanel1.setBackground(new java.awt.Color(159, 164, 169));
        addCustomerPanel1.setForeground(new java.awt.Color(53, 144, 243));
        addCustomerPanel1.setPreferredSize(new java.awt.Dimension(329, 172));

        customerPackageButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        customerPackageButton.setForeground(new java.awt.Color(51, 51, 51));
        customerPackageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isp_manager/resources/package.png"))); // NOI18N
        customerPackageButton.setText("Packages");
        customerPackageButton.setBorder(null);
        customerPackageButton.setContentAreaFilled(false);

        javax.swing.GroupLayout addCustomerPanel1Layout = new javax.swing.GroupLayout(addCustomerPanel1);
        addCustomerPanel1.setLayout(addCustomerPanel1Layout);
        addCustomerPanel1Layout.setHorizontalGroup(
            addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerPackageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addCustomerPanel1Layout.setVerticalGroup(
            addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerPackageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        );

        searchCustomerPanel2.setBackground(new java.awt.Color(159, 164, 169));
        searchCustomerPanel2.setForeground(new java.awt.Color(53, 144, 243));
        searchCustomerPanel2.setPreferredSize(new java.awt.Dimension(329, 172));

        searchCustomerButton.setBackground(new java.awt.Color(51, 51, 51));
        searchCustomerButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        searchCustomerButton.setForeground(new java.awt.Color(51, 51, 51));
        searchCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isp_manager/resources/search.png"))); // NOI18N
        searchCustomerButton.setText("Search Customer");
        searchCustomerButton.setBorder(null);
        searchCustomerButton.setContentAreaFilled(false);

        javax.swing.GroupLayout searchCustomerPanel2Layout = new javax.swing.GroupLayout(searchCustomerPanel2);
        searchCustomerPanel2.setLayout(searchCustomerPanel2Layout);
        searchCustomerPanel2Layout.setHorizontalGroup(
            searchCustomerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );
        searchCustomerPanel2Layout.setVerticalGroup(
            searchCustomerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        );

        listCustomerPanel3.setBackground(new java.awt.Color(159, 164, 169));
        listCustomerPanel3.setForeground(new java.awt.Color(53, 144, 243));
        listCustomerPanel3.setPreferredSize(new java.awt.Dimension(329, 172));

        listOfCustomerButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        listOfCustomerButton.setForeground(new java.awt.Color(51, 51, 51));
        listOfCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isp_manager/resources/customer.png"))); // NOI18N
        listOfCustomerButton.setText("List of Customers");
        listOfCustomerButton.setBorder(null);
        listOfCustomerButton.setContentAreaFilled(false);
        listOfCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOfCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listCustomerPanel3Layout = new javax.swing.GroupLayout(listCustomerPanel3);
        listCustomerPanel3.setLayout(listCustomerPanel3Layout);
        listCustomerPanel3Layout.setHorizontalGroup(
            listCustomerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listOfCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );
        listCustomerPanel3Layout.setVerticalGroup(
            listCustomerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listOfCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );

        customerPaymentPanel.setBackground(new java.awt.Color(159, 164, 169));
        customerPaymentPanel.setPreferredSize(new java.awt.Dimension(329, 172));

        customerPaymentButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        customerPaymentButton.setForeground(new java.awt.Color(51, 51, 51));
        customerPaymentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isp_manager/resources/fees.png"))); // NOI18N
        customerPaymentButton.setText("Customer Payments");
        customerPaymentButton.setBorder(null);
        customerPaymentButton.setContentAreaFilled(false);

        javax.swing.GroupLayout customerPaymentPanelLayout = new javax.swing.GroupLayout(customerPaymentPanel);
        customerPaymentPanel.setLayout(customerPaymentPanelLayout);
        customerPaymentPanelLayout.setHorizontalGroup(
            customerPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerPaymentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );
        customerPaymentPanelLayout.setVerticalGroup(
            customerPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerPaymentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        customerReportPanel.setBackground(new java.awt.Color(159, 164, 169));
        customerReportPanel.setPreferredSize(new java.awt.Dimension(329, 172));

        customerReportButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        customerReportButton.setForeground(new java.awt.Color(51, 51, 51));
        customerReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isp_manager/resources/report.png"))); // NOI18N
        customerReportButton.setText("Reports");
        customerReportButton.setBorder(null);
        customerReportButton.setContentAreaFilled(false);

        javax.swing.GroupLayout customerReportPanelLayout = new javax.swing.GroupLayout(customerReportPanel);
        customerReportPanel.setLayout(customerReportPanelLayout);
        customerReportPanelLayout.setHorizontalGroup(
            customerReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        customerReportPanelLayout.setVerticalGroup(
            customerReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout CustomerPanelLayout = new javax.swing.GroupLayout(CustomerPanel);
        CustomerPanel.setLayout(CustomerPanelLayout);
        CustomerPanelLayout.setHorizontalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchCustomerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerPaymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195)
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addCustomerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(listCustomerPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(customerReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(535, 535, 535))
        );
        CustomerPanelLayout.setVerticalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listCustomerPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(addCustomerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchCustomerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(customerPaymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(CustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerButtonMouseClicked

    private void listOfCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOfCustomerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listOfCustomerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JPanel addCustomerPanel;
    private javax.swing.JPanel addCustomerPanel1;
    private javax.swing.JButton customerPackageButton;
    private javax.swing.JButton customerPaymentButton;
    private javax.swing.JPanel customerPaymentPanel;
    private javax.swing.JButton customerReportButton;
    private javax.swing.JPanel customerReportPanel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel listCustomerPanel3;
    private javax.swing.JButton listOfCustomerButton;
    private javax.swing.JButton searchCustomerButton;
    private javax.swing.JPanel searchCustomerPanel2;
    // End of variables declaration//GEN-END:variables
}
